# Generated by Django 4.2.20 on 2025-04-04 02:09

from django.db import migrations, models
import json.encoder


class Migration(migrations.Migration):

    dependencies = [
        ("image_handle", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="imagecheck",
            options={
                "ordering": ["-check_time"],
                "verbose_name": "图片检测",
                "verbose_name_plural": "图片检测",
            },
        ),
        migrations.AddField(
            model_name="imagecheck",
            name="left_file_name",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="左眼图片名"
            ),
        ),
        migrations.AddField(
            model_name="imagecheck",
            name="left_file_url",
            field=models.URLField(
                blank=True, max_length=250, null=True, verbose_name="左眼图片URL"
            ),
        ),
        migrations.AddField(
            model_name="imagecheck",
            name="right_file_name",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="右眼图片名"
            ),
        ),
        migrations.AddField(
            model_name="imagecheck",
            name="right_file_url",
            field=models.URLField(
                blank=True, max_length=250, null=True, verbose_name="右眼图片URL"
            ),
        ),
        migrations.AlterField(
            model_name="imagecheck",
            name="check_result",
            field=models.JSONField(
                blank=True,
                encoder=json.encoder.JSONEncoder,
                null=True,
                verbose_name="识别结果",
            ),
        ),
        migrations.AlterField(
            model_name="imagecheck",
            name="file_name",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="图片名"
            ),
        ),
        migrations.AlterField(
            model_name="imagecheck",
            name="file_url",
            field=models.CharField(
                blank=True, max_length=250, null=True, verbose_name="图片URL"
            ),
        ),
    ]
