# Generated by Django 4.2.20 on 2025-04-11 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("image_handle", "0003_customuser"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CustomUser",
        ),
    ]
