# Generated by Django 4.2.20 on 2025-04-11 04:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("image_handle", "0004_delete_customuser"),
    ]

    operations = [
        migrations.AddField(
            model_name="imagecheck",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="关联用户",
            ),
        ),
    ]
