"""
Django settings for web_system project.

Generated by 'django-admin startproject' using Django 4.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-0=vbe!mc(cjfbr3vx70#8k%c876=@0nt2pcg28xj44sg9u=bh='

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'simpleui',

    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'image_handle',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    # 'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'web_system.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'front', 'templates')]
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
            'builtins': [
                # 在模板中使用static标签
                'django.templatetags.static'
            ],
        },
    },
]

WSGI_APPLICATION = 'web_system.wsgi.application'

# Database
# https://docs.djangoproject.com/en/4.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# Password validation
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/

LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.0/howto/static-files/

# STATIC_URL should start with a leading slash so URLs resolve correctly from any page.
STATIC_URL = '/static/'

#### 添加以下设置
LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = 'check/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# 配置静态文件
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'front', 'src')
]

# 配置上传文件存储路径
MEDIA_URL = '/image/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media', 'image')



#!!! admin标题
admin_title = '基于低空无人机视觉的桥梁表观病害精细化智能检测系统'
index_info = '''本系统采用领先的深度学习技术，打造专业可靠的桥梁表观病害智能检测平台。系统支持裂缝、剥蚀、锈蚀、病害斑块等内容识别与病情评估。


用户只需上传桥梁表面图像，系统即可快速给出病害类型及置信度，辅助巡检人员实现高效决策和精准维护。'''

# 隐藏右侧SimpleUI广告链接和使用分析
SIMPLEUI_HOME_INFO = False
SIMPLEUI_ANALYSIS = False

# SimpleUI 统一标题配置
SIMPLEUI_TITLE = '基于低空无人机视觉的桥梁表观病害精细化智能检测系统'
SIMPLEUI_HOME_TITLE = '基于低空无人机视觉的桥梁表观病害精细化智能检测系统'
SIMPLEUI_LOGO = '低 空 无 人 机 桥 梁 病 害 精 细 检 测 系 统'
SIMPLEUI_INDEX_TITLE = '欢迎使用基于低空无人机视觉的桥梁表观病害精细化智能检测系统'
SIMPLEUI_CONFIG = {
    'system_name': '基于低空无人机视觉的桥梁表观病害精细化智能检测系统',
    'site_title': '桥梁表观病害精细化智能检测',
    'menu_title': '桥梁病害检测',
    'copyright': '© 2026 桥梁病害检测系统',
    'favicon': 'https://dummyimage.com/16x16/000/fff.png&text=桥'
}

# 关闭浏览器session过期
# SESSION_EXPIRE_AT_BROWSER_CLOSE = True
SESSION_COOKIE_AGE = 60 * 60 * 24
